#!/usr/bin/env python

import subprocess
import sys

try:
    COMMENT_CHAR = (
        subprocess.check_output(["git", "config", "core.commentChar"])
        .decode("utf-8")
        .strip()
        or "#"
    )
except subprocess.CalledProcessError:
    COMMENT_CHAR = "#"

orig_msg_path = sys.argv[1]
with open(orig_msg_path, "rt", encoding="utf-8") as f:
    orig_msg_lines = f.readlines()

try:
    commit_lines = (
        subprocess.check_output(["git", "log", "-5", "--pretty=%s"])
        .decode("utf-8")
        .splitlines()
    )
    git_log_lines = [
        f"{COMMENT_CHAR} Last commits:\n",
        *[f"{COMMENT_CHAR}   {line}\n" for line in commit_lines],
        f"{COMMENT_CHAR}\n",
    ]
except:
    git_log_lines = []

result = []
inserted = False

changes_to_be_commited = [
    f"{COMMENT_CHAR} コミット予定の変更点:",
    f"{COMMENT_CHAR} Changes to be committed:",
]

for line in orig_msg_lines:
    if line.strip() in changes_to_be_commited:
        if result[-1].strip() != COMMENT_CHAR:
            result.append(f"{COMMENT_CHAR}\n")
        result.extend(git_log_lines)
        inserted = True
    elif (
        line.strip()
        == f"{COMMENT_CHAR} ------------------------ >8 ------------------------"
    ):
        # Neovim の tree-sitter は # --- >8 --- な行がないと色が壊れるので無理
        # やり追加する
        result.append(
            f"{COMMENT_CHAR}# ------------------------ >8 ------------------------\n"
        )
    result.append(line)


if not inserted:
    # ここで適当に append してしまうと rebase 時にメッセージが壊れる。
    # rebase で `pick` なコミットを (自動) 適用するときにもこのフックが実行さ
    # れる上にどうも rebase 時はコメントの解釈をしない？のかフォーマットが壊
    # れるのだかわからないが、とにかくコミットメッセージに含まれるようになっ
    # てしまう事故が多発した。
    # result += git_log_lines
    pass


with open(orig_msg_path, "wt", encoding="utf-8") as f:
    f.writelines(result)
